### PR TITLE
refactor: simplify `$RefreshReg$` handling

### PR DESCRIPTION
**Pull request by sapphi-red**
While reviewing #203 I found out that the code can be simplified.

Built on top of #203.

### CODE REVIEW

**Review by ArnaudBarre — COMMENTED** [review]
Yeah I always wondered the need of this boilerplate. The main issue I have with that change is that the preamble is [widely used](https://github.com/search?q=window.%24RefreshSig%24+%3D+%28%29+%3D%3E+%3D%3E+type%3B&type=code) and injected by frameworks and so we should also keep the `window.$RefreshReg$` for the double installed check

**Comment by sapphi-red** [comment]
The document [says the following code needs to be injected](https://vitejs.dev/guide/backend-integration.html#:~:text=Note%20if%20you%20are%20using%20React%20with%20%40vitejs/plugin%2Dreact%2C%20you%27ll%20also%20need%20to%20add%20this%20before%20the%20above%20scripts%2C%20since%20the%20plugin%20is%20not%20able%20to%20modify%20the%20HTML%20you%20are%20serving%20(substitute%20http%3A//localhost%3A5173%20with%20the%20local%20URL%20Vite%20is%20running%20at)%3A).
```js
  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
```
So `window.__vite_plugin_react_preamble_installed__` should be declared as long as they follow the document. The redundant `window.$RefreshReg$`/`$RefreshSig$` won't be a problem.
If we want to keep compat further so that it works with users that dropped `window.__vite_plugin_react_preamble_installed__ = true`, we can change `window.__vite_plugin_react_preamble_installed__ = true` to `window.$RefreshReg$ = () => {}` and `if (window.__vite_plugin_react_preamble_installed__) {` to `if (window.$RefreshReg$) {`.

**Comment by ArnaudBarre** [comment]
I just found that it breaks HMR on one of my utils that was manually registering the created itself with ` window.$RefreshReg$?.(Provider, `${key}Provider`);` (Which could be improved on the transformation because the component is registered for hooks with `$RefreshSig$`);

I did a code search on GitHub but didn't find other usages, but given this is in the [initial guide](https://github.com/facebook/react/issues/16604#issuecomment-528663101) and that it's been used everywhere else I'm not sure it's good that when people come to Vite they have trouble because some lib they used was checking if `$RefreshReg$` is in window as a proxy for dev for ex.

**Comment by sapphi-red** [comment]
Ah, that initial guide is a good point.
I'll close this one.

**Pull request closed without merging**
