### PR TITLE
feat: add parserConfig option

### LINKED ISSUE #182: Plain Vanilla JS files are excluded from SWC processing/transforms
I originally opened the issue here: https://github.com/lingui/swc-plugin/issues/77#issuecomment-1840504440

However it was brought to my attention it's actually this plugin that specifically only runs SWC macros on certain file extensions and excludes plain JS files with extensions .js, .mjs, .cjs, etc.

My argument for including it for plain JS files is that SWC macros cannot be used with plain JS files, when they should be allowed. The normal vite-plugin-react with Babel will transform babel macros for vanilla JS files, but switching to this vite plugin they will not be transformed. The reason I'm using vanilla (.mjs) JS files is because I am using Rescript, and the compiler outputs plain JS files with no types.

Here is the relevant line: https://github.com/vitejs/vite-plugin-react-swc/blob/main/src/index.ts#L206-L217

Here is a sample repo showing the Lingui SWC macro not working: [chrischen/js-lingui@88e8e19](https://github.com/chrischen/js-lingui/commit/88e8e1912cae4ce501dc7985af3fed03aefacc04). The Lingui JS SWC macro specifically has a "js" macro for usage outside of React and in Vanilla JS/TS files. The default behavior of this plugin makes that usage impossible unless it's used in a .ts file.

I believe the solution should be to run even plain JS files through SWC.

### PR DESCRIPTION
**Pull request by ArnaudBarre**
Fixes #182

I didn't go with the classic `include/exclude` because this allow to return parser object and giving full control for the user at very low cost

### CODE REVIEW

**Review by sapphi-red — APPROVED** [review]
LGTM 👍

**Comment by bluwy** [comment]
Personally I'd still lean on include/exclude for consistency and the easier migration from plugin-react. Plus, perhaps one would want the filter function to return more plugin options in the future? Also thinking about Rolldown, there's a chance we could be passing raw glob strings or regex in its API to minimize native<->js calls like esbuild?

**Review by patak-dev — APPROVED** [review]

**Comment by ArnaudBarre** [comment]
My opinion was always to wait the maximum to add this kind of option so when implementing in native we don't need complex configuration and can rely on "standards". This is theoretically nice to be able to switch the config on a per file basis, but once you once used esbuild to bundle a complete React codebase without any plugins you feel the cost of being outside of standards and I want to help people be on the right track for sub-second bundle of real world codebases

**Comment by XantreGodlike** [comment]
I also would like to have an opportunity to use swc for deps to unblock usage of swc plugins

**Comment by bluwy** [comment]
@ArnaudBarre I think that's a fair goal when introducing new options. But if we're introducing a new option that's almost identical to how the ecosystem already implements it, I think it's better to reach directly to it. If we waited for the maximum, we'd have to deprecate `filter` and introduce a migration path which isn't quite nice 🤔

Re-reading the changes, perhaps an option named `parserConfig` would fit better? `filter` for me implies returning a boolean. Also if the API is used, you'd also have to manually replicate the existing TS/MDX handling, is that intentional?

**Comment by ArnaudBarre** [comment]
Yes this is intentional so that it can act as an exclude at the same time and gives you back immediately full control for people that want to oup-out of the default without being complex in the code for us. I'm ok for changing the name so that it's doesn't mislead people that this is can predicate callback

**Comment by bluwy** [comment]
If others are ok I'd prefer renaming the option then 👍  It would also be nice to mention that they need to re-define the config for general TSX/MDX files etc too with this option.

**Comment by sapphi-red** [comment]
Renaming the option to prevent misleading sounds good to me.

**Review by bluwy — APPROVED** [review]

**Pull request merged**
